#!/usr/libexec/platform-python
# -*- coding: utf-8 -*-

# ubi8:ubi:latest ではしらせるときにひつようなパッケージ
# cpio bzip2 
import sys
import os

os.environ['LANG']='C'

DEBUGINFO_RPMS_DIR='./debuginfo_rpms'
USED_RPMS_TXT = 'used_rpms.txt'
DNF='/usr/bin/dnf'
DNF_DEBUGINFO_INSTALL=DNF + ' debuginfo-install'
DEBUG = True


def my_name():
    return sys.argv[0].split('/')[-1]


THIS = my_name()


def debug(message):
    if DEBUG:
        print('debug: ' + message)


def warn(message):
    print('warn: ' + message)


def die_if_not_root():
    if os.geteuid() != 0:
        sys.exit("You need to run " + THIS + " as root.")


def die_if_no_dnf():
    if not os.access(DNF, os.X_OK):
        sys.exit(THIS + ' requires debuginfo-install command.\nRun yum install yum-utils\n')


def make_directory():
    if not os.path.exists(DEBUGINFO_RPMS_DIR):
        os.makedirs(DEBUGINFO_RPMS_DIR)


def get_debuginfo_install_command(packages):
    """
    dnf debuginfo-install --downloadonly --downloaddir DEBUGINFO_RPMS_DIR pkg pkg ...
    """
    command = ' '.join(
        [DNF_DEBUGINFO_INSTALL, '-y', '--downloadonly', '--downloaddir', DEBUGINFO_RPMS_DIR] + packages
    )
    return command


def download_debuginfo(packages):
    command = get_debuginfo_install_command(packages)
    print('Running ' + command)
    os.system(command)


def unpack_debuginfo():
    files = os.listdir(DEBUGINFO_RPMS_DIR)
    for file in files:
        file = DEBUGINFO_RPMS_DIR + '/' + file
        command = 'rpm2cpio ' + file + ' | cpio -idu'
        print('Running ' + command)
        os.system(command)


def parse_used_rpms_txt():
    packages = []
    with open(USED_RPMS_TXT, 'r') as f:
        for line in set([line.rstrip() for line in f.readlines()]):
            tokens = line.split()
            if len(tokens)>1:
                warn("parse_relatedrpms: " + line)
            else:
                warn(line)
                packages.append(line)
    return packages


def main():
    die_if_not_root()
    die_if_no_dnf()
    make_directory()
    packages = parse_used_rpms_txt()
    download_debuginfo(packages)
    unpack_debuginfo()
    sys.exit('\n\nDebuginfo provided.\nRun ./opencore.sh')

if __name__ == '__main__':
    if os.path.abspath(__file__).endswith('test'):
        import doctest
        doctest.testmod(verbose=True)
        sys.exit(0)
    main()
